import { z } from 'zod'

// ----------------------------------------------------------------------------
// Scenario file format (plancraft v1)
//
// A scenario is a self-contained description of a household's financial
// trajectory in the vocabulary of decisions and events (income phases,
// expenses, one-time purchases), expressed entirely in REAL (inflation
// adjusted), AFTER-TAX dollars. It compiles down to a standard TPAW Planner
// `PlanParams` object, so anything expressible here is by construction
// something the real planner at tpawplanner.com accepts.
//
// The schema is designed to be generated by an LLM from a financial plan
// document or interview. Every field carries a description; the generated
// JSON Schema (docs/scenario.schema.json) is the machine-readable contract.
// ----------------------------------------------------------------------------

const ageYearsMonths = z
  .object({
    years: z.number().int().gte(0).lte(115).describe('Whole years.'),
    months: z
      .number()
      .int()
      .gte(0)
      .lte(11)
      .optional()
      .describe('Additional months, 0-11. Defaults to 0.'),
  })
  .describe('An age expressed as years plus optional months.')

const personId = z
  .enum(['person1', 'person2'])
  .describe("Which household member. 'person1' is the primary.")

const timePoint = z
  .union([
    z
      .object({
        calendarYear: z
          .number()
          .int()
          .gte(1900)
          .lte(2200)
          .describe('Calendar year, e.g. 2031.'),
        month: z
          .number()
          .int()
          .gte(1)
          .lte(12)
          .optional()
          .describe('Calendar month 1-12. Defaults to January.'),
      })
      .describe(
        'A calendar date. Interpreted relative to the scenario anchor year ' +
          '(meta.anchorYear): the compiler converts it to person1\'s age at ' +
          'that date, so the scenario stays reproducible over time.',
      ),
    z
      .object({
        age: z
          .object({
            person: personId
              .optional()
              .describe("Defaults to 'person1'."),
            years: z.number().int().gte(0).lte(115),
            months: z.number().int().gte(0).lte(11).optional(),
          })
          .describe('An age of a household member.'),
      })
      .describe("A point in time expressed as a person's age."),
    z
      .object({
        named: z
          .enum(['now', 'lastWorkingMonth', 'retirement', 'maxAge'])
          .describe(
            "'now' = the present. 'lastWorkingMonth' = the month before " +
              "retirement. 'retirement' = the retirement month. 'maxAge' = " +
              'end of plan (death age).',
          ),
        person: personId
          .optional()
          .describe("Whose milestone (ignored for 'now'). Defaults to 'person1'."),
      })
      .describe('A named milestone.'),
  ])
  .describe(
    'A point in time: a calendar date, an age, or a named milestone.',
  )
export type TimePoint = z.infer<typeof timePoint>

const timingRange = z
  .union([
    z
      .object({
        from: timePoint.describe('First month of the range (inclusive).'),
        to: timePoint.describe('Last month of the range (inclusive).'),
      })
      .describe('A range given by start and end.'),
    z
      .object({
        from: timePoint.describe('First month of the range (inclusive).'),
        durationYears: z
          .number()
          .gt(0)
          .lte(120)
          .describe('Length of the range in years (may be fractional).'),
      })
      .describe('A range given by start and duration.'),
  ])
  .describe('A span of months over which a recurring amount applies.')
export type TimingRange = z.infer<typeof timingRange>

const eventKind = z
  .enum(['savings', 'retirementIncome', 'expenseEssential', 'expenseDiscretionary'])
  .describe(
    "What the money flow is. 'savings': net contribution to the portfolio " +
      'before retirement (income minus all regular spending and taxes; also ' +
      "use a one-time 'savings' event for a windfall). " +
      "'retirementIncome': income arriving during retirement (Social " +
      'Security, pension, part-time work after retirement). ' +
      "'expenseEssential': a must-fund expense drawn from the portfolio at " +
      'any time, pre- or post-retirement (mortgage years, daycare, school ' +
      'tuition, a one-time house down payment or car purchase) - funded ' +
      "conservatively by the planner. 'expenseDiscretionary': a nice-to-have " +
      'expense (travel, upgrades) the planner may scale back in bad markets. ' +
      'Amounts must be >= 0: model windfalls as savings/income events, never ' +
      'as negative expenses.',
  )
export type EventKind = z.infer<typeof eventKind>

const scenarioEvent = z
  .object({
    id: z
      .string()
      .regex(/^[a-zA-Z0-9_-]{1,40}$/)
      .describe(
        'Stable identifier, unique within the scenario. Used by composition ' +
          '(a later file can replace or exclude an event by id).',
      ),
    label: z
      .string()
      .max(150)
      .optional()
      .describe('Human-readable label shown in reports and the planner UI.'),
    kind: eventKind,
    nominal: z
      .boolean()
      .optional()
      .describe(
        'If true the amount is in nominal (then-current) dollars rather ' +
          'than real dollars. Default false (real dollars) - recommended.',
      ),
    amount: z
      .union([
        z
          .object({ perMonth: z.number().gte(0) })
          .describe('Recurring amount per month, in dollars.'),
        z
          .object({ perYear: z.number().gte(0) })
          .describe(
            'Recurring amount per year, in dollars (compiled to a monthly ' +
              'amount, rounded to whole dollars).',
          ),
        z
          .object({ oneTime: z.number().gte(0) })
          .describe('A single lump-sum amount, in dollars.'),
      ])
      .describe(
        'Dollar amount. Real, after-tax dollars unless nominal is true.',
      ),
    timing: z
      .union([
        z
          .object({ at: timePoint })
          .describe('When a one-time amount occurs. Requires amount.oneTime.'),
        timingRange,
      ])
      .describe(
        'When the flow occurs: {at} for one-time amounts, a range for ' +
          'recurring amounts.',
      ),
  })
  .describe(
    'One money flow. Model income steps (e.g. fellowship then attending ' +
      'salary) or part-time phases as consecutive savings events with ' +
      'different amounts and adjacent ranges.',
  )
export type ScenarioEvent = z.infer<typeof scenarioEvent>

const person = z
  .object({
    currentAge: ageYearsMonths.describe('Age today.'),
    retirementAge: ageYearsMonths.describe(
      'Planned retirement age. If already retired, set equal to currentAge.',
    ),
    maxAge: ageYearsMonths
      .optional()
      .describe('Plan-until age (death age). Defaults to 100.'),
  })
  .describe('One household member.')
export type ScenarioPerson = z.infer<typeof person>

const simulationSettings = z
  .object({
    strategy: z
      .enum(['TPAW', 'SPAW', 'SWR'])
      .optional()
      .describe(
        "Withdrawal/allocation strategy. Default 'TPAW' (amortization based " +
          'with Merton-derived allocation).',
      ),
    expectedReturns: z
      .union([
        z
          .object({
            fixed: z.object({
              stocks: z
                .number()
                .gte(-0.01)
                .lte(0.1)
                .describe('Expected annual real stock return, e.g. 0.05.'),
              bonds: z
                .number()
                .gte(-0.01)
                .lte(0.1)
                .describe('Expected annual real bond return, e.g. 0.02.'),
            }),
          })
          .describe(
            'Fixed expected returns (rounded to 0.1% steps). Recommended ' +
              'for reproducible scenario comparison.',
          ),
        z
          .object({
            preset: z.enum([
              'regressionPrediction,20YearTIPSYield',
              'conservativeEstimate,20YearTIPSYield',
              '1/CAPE,20YearTIPSYield',
              'historical',
            ]),
          })
          .describe(
            "A tpawplanner preset that derives expected returns from " +
              'current market data (varies day to day).',
          ),
      ])
      .optional()
      .describe(
        "Expected returns for planning. Default: the planner's default " +
          "preset ('regressionPrediction,20YearTIPSYield').",
      ),
    inflation: z
      .union([
        z
          .object({
            manual: z
              .number()
              .gte(-0.01)
              .lte(0.1)
              .describe('Annual inflation rate, e.g. 0.024.'),
          })
          .describe('Fixed annual inflation (rounded to 0.1% steps).'),
        z.literal('suggested').describe('Market-derived breakeven inflation.'),
      ])
      .optional()
      .describe(
        'Inflation assumption (only affects nominal amounts and display). ' +
          "Default 'suggested'.",
      ),
    sampling: z
      .union([
        z
          .object({
            type: z.literal('monteCarlo'),
            numRuns: z
              .number()
              .int()
              .gte(1)
              .lte(5000)
              .optional()
              .describe(
                'Number of Monte Carlo runs. Default 2000. The hosted ' +
                  'simulator supports up to 5000.',
              ),
            seed: z
              .number()
              .int()
              .gte(0)
              .optional()
              .describe(
                'Random seed. Default 1776. Keep identical across compared ' +
                  'scenarios.',
              ),
            blockSizeYears: z
              .number()
              .gt(0)
              .lte(30)
              .optional()
              .describe('Block-bootstrap block size in years. Default 5.'),
            staggerRunStarts: z.boolean().optional().describe('Default true.'),
          })
          .describe('Monte Carlo (block bootstrap over historical returns).'),
        z
          .object({ type: z.literal('historical') })
          .describe('Rolling historical windows (deterministic).'),
      ])
      .optional()
      .describe("Return-sequence sampling. Default Monte Carlo."),
    percentiles: z
      .array(z.number().int().gte(1).lte(99))
      .min(1)
      .max(9)
      .optional()
      .describe(
        'Percentiles to report for trajectories. Default [5, 25, 50, 75, 95].',
      ),
    riskTolerance: z
      .number()
      .int()
      .gte(0)
      .lte(24)
      .optional()
      .describe(
        'TPAW risk tolerance at age 20, integer 0-24 (0 most conservative; ' +
          '12 = default "Moderate").',
      ),
    spendingCeiling: z
      .number()
      .gte(0)
      .nullable()
      .optional()
      .describe('Monthly spending ceiling in dollars. Default none.'),
    spendingFloor: z
      .number()
      .gte(0)
      .nullable()
      .optional()
      .describe('Monthly spending floor in dollars. Default none.'),
    legacy: z
      .number()
      .gte(0)
      .optional()
      .describe('Target legacy (bequest) in real dollars. Default 0.'),
    stockAllocation: z
      .object({
        start: z.number().gte(0).lte(1),
        end: z.number().gte(0).lte(1),
      })
      .optional()
      .describe(
        'Stock allocation glide path (start = now, end = maxAge), used only ' +
          'by SPAW and SWR strategies. TPAW derives allocation itself. ' +
          'Default 0.5/0.5.',
      ),
    swrWithdrawal: z
      .union([
        z.object({ percentPerYear: z.number().gte(0).lte(1) }),
        z.object({ amountPerMonth: z.number().int().gte(0) }),
      ])
      .optional()
      .describe(
        "SWR strategy only: the withdrawal rule. Default: tpawplanner's " +
          'retirement-length-derived percentage.',
      ),
  })
  .describe('Simulation settings, all optional with TPAW Planner defaults.')
export type SimulationSettings = z.infer<typeof simulationSettings>

export const scenarioFileSchema = z
  .object({
    plancraft: z.literal(1).describe('Scenario format version. Must be 1.'),
    meta: z
      .object({
        name: z.string().min(1).max(80).describe('Scenario name.'),
        description: z.string().max(2000).optional(),
        anchorYear: z
          .number()
          .int()
          .gte(1900)
          .lte(2200)
          .optional()
          .describe(
            'The calendar year that "now" corresponds to. Calendar-date ' +
              'timings are converted to ages relative to this. Defaults to ' +
              'the current year at compile time; set it explicitly for ' +
              'reproducibility.',
          ),
        marketDataDate: z
          .string()
          .regex(/^\d{4}-\d{2}-\d{2}$/)
          .optional()
          .describe(
            'YYYY-MM-DD date whose end-of-day market data the plan is ' +
              'frozen at (plans are "dateless" for reproducibility). ' +
              'Defaults to the most recent date the planner supports.',
          ),
      })
      .describe('Scenario identity and reproducibility anchors.'),
    household: z
      .object({
        person1: person,
        person2: person.optional().describe('Partner, if any.'),
        withdrawalStart: personId
          .optional()
          .describe(
            'With a partner: whose retirement begins portfolio withdrawals ' +
              "(the household's \"retirement\" boundary). Defaults to 'person1'.",
          ),
      })
      .describe('Who the plan is for.'),
    portfolio: z
      .object({
        balance: z
          .number()
          .gte(0)
          .describe('Current investable portfolio balance in dollars.'),
      })
      .describe('Current portfolio.'),
    events: z
      .array(scenarioEvent)
      .max(80)
      .describe(
        'All money flows. The portfolio evolves from the current balance ' +
          'plus savings, minus expenses, with retirement spending computed ' +
          'by the strategy.',
      ),
    simulation: simulationSettings.optional(),
    composition: z
      .object({
        extends: z
          .string()
          .optional()
          .describe(
            'Relative path to a base scenario file. This file inherits ' +
              'everything from the base; fields given here win, and events ' +
              'merge by id (same id replaces the base event).',
          ),
        include: z
          .array(z.string())
          .optional()
          .describe(
            'Relative paths to event-fragment files ({ events: [...] }) ' +
              'merged in after extends, in order, by id.',
          ),
        excludeEventIds: z
          .array(z.string())
          .optional()
          .describe('Event ids to remove after all merging.'),
      })
      .optional()
      .describe('Lightweight scenario composition.'),
  })
  .describe(
    'A plancraft scenario: a household financial trajectory in real, ' +
      'after-tax dollars, compiled to a TPAW Planner plan.',
  )

export type ScenarioFile = z.infer<typeof scenarioFileSchema>

// A fragment file may contain only events (used via composition.include).
export const eventFragmentFileSchema = z
  .object({
    plancraft: z.literal(1),
    events: z.array(scenarioEvent).max(80),
  })
  .describe('An event-fragment file: only events, merged into scenarios.')
export type EventFragmentFile = z.infer<typeof eventFragmentFileSchema>

// A scenario file as authored may be partial when it extends a base. We
// validate the *resolved* scenario against scenarioFileSchema; authored
// files are validated leniently.
export const authoredScenarioFileSchema = scenarioFileSchema
  .partial()
  .extend({
    plancraft: z.literal(1),
    meta: scenarioFileSchema.shape.meta,
    // Deep-partial household so a variant can override just one person (the
    // resolved scenario is still validated against the full schema).
    household: z
      .object({
        person1: person.optional(),
        person2: person.optional(),
        withdrawalStart: personId.optional(),
      })
      .optional(),
  })
export type AuthoredScenarioFile = z.infer<typeof authoredScenarioFileSchema>
